<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="e5d6f10c-7507-49da-9457-2db11cbd7e7d">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/sitioWeb/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:C:\Users\darkl\Documents\Github\muedatos2\sitioWeb\db.sqlite3</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="Django atencionCliente" uuid="ba51bc15-47dd-47f8-954e-9efc52953543">
      <driver-ref>mysql.8</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/sitioWeb/settings.py</remarks>
      <jdbc-driver>com.mysql.cj.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://127.0.0.1:3306/atencioncliente</jdbc-url>
      <driver-properties>
        <property name="serverTimezone" value="UTC" />
      </driver-properties>
    </data-source>
    <data-source source="LOCAL" name="taller" uuid="97396978-1e71-4ee1-ad69-b398368d7e62">
      <driver-ref>sqlserver.ms</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>com.microsoft.sqlserver.jdbc.SQLServerDriver</jdbc-driver>
      <jdbc-url>jdbc:sqlserver://localhost;database=taller</jdbc-url>
    </data-source>
  </component>
</project>